services:
  semi-detr-cu111-torch190:
    shm_size: '8gb'
    runtime: nvidia
    labels:
      - "role=development"
    deploy:
      resources:
        limits:
          memory: 14G
    build:
      # context: .
      dockerfile: Dockerfile
      # dockerfile: sly_net.Dockerfile
      # dockerfile: vscode-old-linux.Dockerfile
      args:
        # IMAGE: paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4
        # IMAGE: supervisely/rt-detrv2:1.0.23
        # IMAGE: supervisely/apply-nn-to-videos-project:1.0.5
        # IMAGE: supervisely/deim:1.0.0
        # IMAGE: supervisely/mvd:dev
        # IMAGE: supervisely/mouse-action-recognition:1.0.0
        # IMAGE: supervisely/florence-2:1.0.1
        # IMAGE: supervisely/mmdet:1.0.15
        IMAGE: pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel
    cap_add:
      - NET_ADMIN
    env_file: ~/supervisely.env
    environment:
      - DEBIAN_FRONTEND=noninteractive
    # ports:
    #   - "8000:8001"
    volumes:
      - "~/volume:/root/volume"
    # restart: always
    entrypoint:
      - /usr/sbin/sshd
      - -D
