services:
  efficientnet-cu128:
    shm_size: '8gb'
    runtime: nvidia
    labels:
      - "role=development"
    deploy:
      resources:
        limits:
          memory: 14G
    build:
      # context: .
      dockerfile: Dockerfile
      # dockerfile: sly_net.Dockerfile
      # dockerfile: comfyui_env.Dockerfile
      args:
        # IMAGE: paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4
        # IMAGE: supervisely/rt-detrv2:1.0.23
        # IMAGE: supervisely/apply-nn-to-videos-project:1.0.5
        # IMAGE: supervisely/mmdet-3.3.0-cu121
        # IMAGE: supervisely/mmdet-v3.3.0-cu128:v4
        # IMAGE: supervisely/mmseg-v1.2.2-cu128:v1.0.6
        IMAGE: supervisely/efficient-net-v2:dev
    cap_add:
      - NET_ADMIN
    env_file: ~/supervisely.env
    environment:
      - DEBIAN_FRONTEND=noninteractive
    # ports:
    #   - "8000:8001"
    volumes:
      - "~/volume:/root/volume"
    # restart: always
    entrypoint:
      - /usr/sbin/sshd
      - -D
