services:
  action-recognition:
    shm_size: '8gb'
    runtime: nvidia
    labels:
      - "role=development"
    deploy:
      resources:
        limits:
          memory: 14G
    build:
      # context: .
      # dockerfile: Dockerfile
      dockerfile: sly_net.Dockerfile
      # dockerfile: comfyui_env.Dockerfile
      args:
        # IMAGE: supervisely/base-py-sdk:6.72.2
        # IMAGE: supervisely/ritm:1.2.0
        # IMAGE: supervisely/ritm-training:1.1.4
        # IMAGE: supervisely/cotracker:1.0.1
        # IMAGE: supervisely/detectron2:1.0.5
        # IMAGE: paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4
        # IMAGE: supervisely/hrda:1.0.0
        # IMAGE: supervisely/mmseg:1.3.4
        # IMAGE: supervisely/mmdet-3.0:1.0.10
        # IMAGE: supervisely/mmcls:1.0.1
        # IMAGE: supervisely/serve-clickseg:1.0.5
        # IMAGE: supervisely/mmdet3d-v1.x
        # IMAGE: supervisely/langchain:1.0.0
        # IMAGE: supervisely/rt-detr:1.0.0
        # IMAGE: supervisely/yolov8:1.0.40
        IMAGE: supervisely/rt-detrv2:1.0.7
        # IMAGE: supervisely/apply-nn-to-videos-project:1.0.5
    cap_add:
      - NET_ADMIN
    env_file: ~/supervisely.env
    environment:
      - DEBIAN_FRONTEND=noninteractive
    # ports:
    #   - "9706:22"
    volumes:
      - "~/volume:/root/volume"
    # restart: always
    entrypoint:
      - /usr/sbin/sshd
      - -D
