services:
  rtdetrv2-deploy:
    shm_size: '4gb'
    runtime: nvidia
    image: supervisely/rt-detrv2:1.0.3
    env_file: ~/supervisely.env
    environment:
      - LOCAL_DEPLOY=True
      - TEAM_ID=440
      - PYTHONPATH=/app:/app/supervisely_integration
    volumes:
      - ./RT-DETRv2:/app
      - ~/volume/data:/data
    entrypoint:
      "python3 supervisely_integration/serve/main.py --model RT-DETRv2-S --predict-project-id 32510"
    working_dir: /app