services:
  playwright-test:
    shm_size: '2gb'
    runtime: nvidia
    labels:
      - "role=development"
    deploy:
      resources:
        limits:
          memory: 14G
    build:
      # context: .
      dockerfile: Dockerfile
      args:
        IMAGE: claude-playwright-test
    cap_add:
      - NET_ADMIN
    env_file: ~/supervisely.env
    environment:
      - DEBIAN_FRONTEND=noninteractive
    # ports:
    #   - "8000:8001"
    volumes:
      - "~/volume:/root/volume"
    # restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
